apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-credential
  annotations:
    tekton.dev/docker-0: https://index.docker.io # Described below
type: kubernetes.io/basic-auth
stringData:
  username: YOUR_DOCKERHUB_USERNAME
  password: YOUR_DOCKERHUB_PASSWORD
