apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: target-docker-hub-registry
spec:
  type: image
  params:
    - name: url
      value: index.docker.io/marthenl/petclinic-mysql-native-image
