FROM openjdk:12-alpine

ARG ORACLE_PORT=1521
ARG ORACLE_HOST=host.docker.internal
ARG ORACLE_SERVICE_NAME=orclpdb1.localdomain
ARG DO_NOT_INITIALIZE=always
ARG MAX_HEAP=200m

ENV MYSQL_HOST=mysql \
    DO_NOT_INITIALIZE=$DO_NOT_INITIALIZE \
    ORACLE_HOST=$ORACLE_HOST \
    ORACLE_SERVICE_NAME=$ORACLE_SERVICE_NAME \
    ORACLE_PORT=$ORACLE_PORT \
    VERSION=v0.8
RUN mkdir -p /home/app/petclinic
WORKDIR /home/app/petclinic

COPY ./target/petclinic-jpa-0.0.1-SNAPSHOT.jar .

# Install psrecord
RUN apk add --update alpine-sdk openssl-dev build-base
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN apk add --update --no-cache py3-psutil
RUN rm -rf /var/cache/apk/*
RUN pip install --upgrade pip
RUN pip install psrecord

EXPOSE 8080
ENTRYPOINT ["psrecord", "java -Xmx150m -jar ./petclinic-jpa-0.0.1-SNAPSHOT.jar", "--log", "/reports/profile.prof"]
