apiVersion: v1
kind: Service
metadata:
  name: oradb
spec:
  ports:
    - protocol: TCP
      port: 1521
      targetPort: 1521
  selector:
    app: oradb
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oradb1
  labels:
    app: oradb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oradb
  template:
    metadata:
      labels:
        app: oradb
    spec:
      containers:
        - name: oradb01
          image: store/oracle/database-enterprise:12.2.0.1-slim
          ports:
            - containerPort: 1521